datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        uid: influxdb
        database: ${INFLUXDB_CONNECT_DBNAME}
        url: http://${INFLUXDB_CONNECT_ADDRESS}:${INFLUXDB_CONNECT_PORT}
        user: ${INFLUXDB_CONNECT_DBUSER}
        secureJsonData:
          password: ${INFLUXDB_CONNECT_PASSWORD}
        jsonData:
          httpMode: GET

envValueFrom:
  INFLUXDB_CONNECT_DBNAME:
    secretKeyRef:
      name: influxdb-auth
      key: influxdb-db
  INFLUXDB_CONNECT_DBUSER:
    secretKeyRef:
      name: influxdb-auth
      key: influxdb-user
  INFLUXDB_CONNECT_PASSWORD:
    secretKeyRef:
      name: influxdb-auth
      key: influxdb-password
  INFLUXDB_CONNECT_ADDRESS:
    secretKeyRef:
      name: pgwatch2-secret
      key: pgwatch2-ihost
  INFLUXDB_CONNECT_PORT:
    secretKeyRef:
      name: pgwatch2-secret
      key: pgwatch2-iport

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: true
      editable: false
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    db-overview:
      file: dashboards/db-overview.json