apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: influxdb
  namespace: grafana
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: influxdb
  ingress:
    - {}
  policyTypes:
    - Ingress
