apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: postgresql
  ports:
    - protocol: TCP
      port: 5432  # Default PostgreSQL port
      targetPort: 5432
      nodePort: 30000  # Port on which you want to access PostgreSQL from localhost
