extraDeploy:
  - apiVersion: v1
    kind: Service
    metadata:
      name: postgresql-np
    spec:
      type: NodePort
      selector:
        app.kubernetes.io/name: postgresql
      ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
          nodePort: 30000


primary:
  configuration: |
    shared_preload_libraries = 'pg_stat_statements'
    pg_stat_statements.track = all