apiVersion: v1
kind: Service
metadata:
  name: argocd
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30001
